spring:
  application:
    name: ex-world-engine
  docker:
    compose:
      file: ../../../../ex-infra/apps/exchange/ex-infra/docker-compose.yml
      profiles:
        active: ai
      lifecycle-management: start_only

  ai:
    chat:
      client:
        enabled: false

    openai:
      api-key: ${AI_HUB_API_KEY}
      base-url: https://adesso-ai-hub.3asabc.de
      chat:
        options:
          model: gpt-oss-120b-sovereign

    # this section is customized to define and define dedicated embedding model
    dedicated-embedding:
      enabled: true
      #provider: openai
      #api-key: ${AI_HUB_API_KEY}
      #base-url: https://adesso-ai-hub.3asabc.de
      #model: text-embedding-3-large
      provider: ollama
      #api-key: ${AI_HUB_API_KEY}
      base-url: http://localhost:11434
      model: embeddinggemma

    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        initialize-schema: false
        collections:
          news: news
          story_threads: threads

app:
  catch-up-generation: true

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG