spring:
  application:
    name: ex-world-engine
  docker:
    compose:
      file: ../../../../ex-infra/apps/exchange/ex-infra/docker-compose.yml
      profiles:
        active: ai
      lifecycle-management: start_only

  ai:
    chat:
      client:
        enabled: false

    openai:
      api-key: ${AI_HUB_API_KEY}
      base-url: https://adesso-ai-hub.3asabc.de

    # this section is customized to define and define dedicated embedding model
    dedicated-embedding:
      enabled: true
      #provider: openai
      #api-key: ${AI_HUB_API_KEY}
      #base-url: https://adesso-ai-hub.3asabc.de
      #model: text-embedding-3-large
      provider: ollama
      #api-key: ${AI_HUB_API_KEY}
      base-url: http://localhost:11434
      model: embeddinggemma

    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: news
        initialize-schema: true
        # custom parameter to compare dimension of embedding model with dimension of collection
        validate-schema-dimension: true

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG